<h3>Admin Helmut Dashboard</h3>


<a class="btn btn-primary" href="<?=$this->url('helmut-producto/default',array('controller'=>'index','action'=>'config'))?>">Ver Config</a>
<a class="btn btn-primary" href="<?=$this->url('helmut-producto/default',array('controller'=>'index','action'=>'login'))?>">Login</a>
<a class="btn btn-primary" href="<?=$this->url('helmut-producto/default',array('controller'=>'producto','action'=>'index'))?>">Producto</a>

