<h3>Admin Dashboard</h3>

<?php //var_dump('Vista index');?>

<a class="btn btn-primary" href="<?=$this->url('karina/default',array('controller'=>'index','action'=>'config'))?>">Ver Config</a>
<a class="btn btn-primary" href="<?=$this->url('karina/default',array('controller'=>'index','action'=>'login'))?>">Login</a>
<a class="btn btn-primary" href="<?=$this->url('karina/default',array('controller'=>'categoria','action'=>'index'))?>">Categoría</a>

