<div class="row">

    <h2>Form</h2>

    <ul>
        <li><a href="<?=$this->url('tema-form/default',array('controller'=>'index','action'=>'basico'))?>">Básico</a></li>
        <li><a href="<?=$this->url('tema-form/default',array('controller'=>'index','action'=>'clase-form'))?>">Clase Form</a></li>
        <li><a href="<?=$this->url('tema-form/default',array('controller'=>'index','action'=>'clase-form-en-post'))?>">Clase Form en POST</a></li>
        <li><a href="<?=$this->url('tema-form/default',array('controller'=>'index','action'=>'input-filter'))?>">Input Filter</a></li>
    </ul>
    
</div>
