
<div class="row">

    <h1>Tema HttpClient</h1>
    
    <ul>
        <li><a href="<?=$this->url('tema-http-client/default',array('controller'=>'index','action'=>'listar'))?>">Listar</a></li>
        <li><a href="<?=$this->url('tema-http-client/default',array('controller'=>'index','action'=>'ver-detalle'))?>">Ver Detalle</a></li>
        <li><a href="<?=$this->url('tema-http-client/default',array('controller'=>'index','action'=>'nuevo'))?>">Nuevo</a></li>
        <li><a href="<?=$this->url('tema-http-client/default',array('controller'=>'index','action'=>'editar'))?>">Editar</a></li>
        <li><a href="<?=$this->url('tema-http-client/default',array('controller'=>'index','action'=>'borrar'))?>">Borrar</a></li>
    </ul>
    
</div>
