<div class="row">

    <h2>Db</h2>

    <ul>
        <li><a href="<?=$this->url('tema-db/default',array('controller'=>'index','action'=>'table-gateway'))?>">TableGateway</a></li>
        <li><a href="<?=$this->url('tema-db/default',array('controller'=>'index','action'=>'table-gateway-result-set-iterado'))?>">TableGateway, ResulSet iterado</a></li>
        <li><a href="<?=$this->url('tema-db/default',array('controller'=>'index','action'=>'table-gateway-result-set-array'))?>">TableGateway, ResulSet array</a></li>
        <li><a href="<?=$this->url('tema-db/default',array('controller'=>'index','action'=>'table-gateway-result-set-prototype'))?>">TableGateway, ResulSet Prototype</a></li>
        <li><a href="<?=$this->url('tema-db/default',array('controller'=>'index','action'=>'table-gateway-select-string'))?>">TableGateway -> select (string) </a></li>
        <li><a href="<?=$this->url('tema-db/default',array('controller'=>'index','action'=>'table-gateway-select-array'))?>">TableGateway -> select (array) </a></li>
        <li><a href="<?=$this->url('tema-db/default',array('controller'=>'index','action'=>'select-closure'))?>">Select Closure</a></li>
        <li><a href="<?=$this->url('tema-db/default',array('controller'=>'index','action'=>'select-cols-array'))?>">Select cols array</a></li>
        <li><a href="<?=$this->url('tema-db/default',array('controller'=>'index','action'=>'select-cols-array-alias'))?>">Select cols array alias</a></li>
        <li><a href="<?=$this->url('tema-db/default',array('controller'=>'index','action'=>'join'))?>">Join</a></li>
        <li><a href="<?=$this->url('tema-db/default',array('controller'=>'index','action'=>'insert'))?>">Insert</a></li>
        <li><a href="<?=$this->url('tema-db/default',array('controller'=>'index','action'=>'update'))?>">Update</a></li>
        <li><a href="<?=$this->url('tema-db/default',array('controller'=>'index','action'=>'delete'))?>">Delete</a></li>
    </ul>
    
</div>
