<a class="btn btn-default" href="<?=$this->url('vitucho/default',array('controller'=>'index','action'=>'index'))?>">Back</a>
<a class="btn btn-primary" href="<?=$this->url('vitucho/default',array('controller'=>'proveedor','action'=>'nuevo'))?>">Nuevo</a>


<div class="row">
    <h1>Admin - Proveedor</h1>
<style>
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('/fonts/glyphicons-halflings-regular.eot');
  src: url('/fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'),
       url('/fonts/glyphicons-halflings-regular.woff') format('woff'),
       url('/fonts/glyphicons-halflings-regular.ttf') format('truetype'),
       url('/fonts/glyphicons-halflings-regular.svg#glyphicons-halflingsregular') format('svg');
}        
</style>    
    
<?php
$qsa = $this->qs;
$urlBase = $this->url('vitucho/default',array('controller'=>'proveedor','action'=>'index'));
$mask = '<a class="btn btn-primary" href="%s">%s <span class="glyphicon glyphicon-chevron-%s"></span></a>';

$dir = 'ASC';
$orden = 'ruc';
$qsa['dir'] = $dir;
$qsa['orden'] = $orden;
$u = $urlBase.'?'.http_build_query($qsa);
echo sprintf($mask,$u,$orden,$dir=='ASC'?'down':'up');

$dir = 'DESC';
$orden = 'ruc';
$qsa['dir'] = $dir;
$qsa['orden'] = $orden;
$u = $urlBase.'?'.http_build_query($qsa);
echo sprintf($mask,$u,$orden,$dir=='ASC'?'down':'up');

$dir = 'ASC';
$orden = 'email';
$qsa['dir'] = $dir;
$qsa['orden'] = $orden;
$u = $urlBase.'?'.http_build_query($qsa);
echo sprintf($mask,$u,$orden,$dir=='ASC'?'down':'up');

$dir = 'DESC';
$orden = 'email';
$qsa['dir'] = $dir;
$qsa['orden'] = $orden;
$u = $urlBase.'?'.http_build_query($qsa);
echo sprintf($mask,$u,$orden,$dir=='ASC'?'down':'up');

?>
    
    
    <table class="table">
        <thead>
            <tr>
                <th>Proveedor</th>
                <th>RUC</th>
                <th>Email</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($this->rows as $row): ?>
            <tr class="<?=$row->getActivo()?'activo':'inactivo'?>">
                <? $id = $row->getId() ?>
                <td><?=$row->getNombre()?></td>
                <td><?=$row->getRuc()?></td>
                <td><?=$row->getEmail()?></td>
                <td>
                    <? $base = array('controller'=>'proveedor','id'=>$id) ?>
                    <? $url = $this->url('vitucho/default/id',  array_merge($base,array('action'=>'editar'))) ?>
                    <a href="<?=$url?>" class="btn btn-primary btn-xs">editar</a>
                    
                    <? if(!$row->getActivo()): ?>
                        <? $url = $this->url('vitucho/default/id',  array_merge($base,array('action'=>'activar'))) ?>
                        <a onclick="return confirm('Seguro?')" href="<?=$url?>" class="btn btn-primary btn-xs">activar</a>
                    <? else: ?>
                        <? $url = $this->url('vitucho/default/id',  array_merge($base,array('action'=>'desactivar'))) ?>
                        <a onclick="return confirm('Seguro?')" href="<?=$url?>" class="btn btn-primary btn-xs">desactivar</a>
                    <? endif; ?>
                    
                    <? $url = $this->url('vitucho/default/id',  array_merge($base,array('action'=>'borrar'))) ?>
                    <a onclick="return confirm('Seguro?')" href="<?=$url?>" class="btn btn-warning btn-xs">borrar</a>
                </td>
            </tr>
            <? endforeach; ?>
        </tbody>
    </table>
    
     <?php 
    echo $this->paginationControl(
            // el objeto paginador
        $this->rows,
            // estilo
            'sliding',
            // el partial del control paginador
        array('vitucho/proveedor/_pag.phtml','Vitucho'),
            // La ruta de los enlaces
        array(
            'route' => 'vitucho/default',
            'routeArgs' => array('controller'=>'proveedor','action'=>'index'),
        )
    ); 
    ?>
    
</div>

<style>
    table tbody tr.activo {
        background-color: lightgreen;
    }
    table tbody tr.inactivo {
        background-color: salmon;
    }
</style>