<h3>Admin Dashboard</h3>


<a class="btn btn-primary" href="<?=$this->url('admin/default',array('controller'=>'index','action'=>'config'))?>">Ver Config</a>
<a class="btn btn-primary" href="<?=$this->url('admin/default',array('controller'=>'index','action'=>'login'))?>">Login</a>
<a class="btn btn-primary" href="<?=$this->url('admin/default',array('controller'=>'categoria','action'=>'index'))?>">Categoría</a>




<h3>Vitucho</h3>

<a class="btn btn-primary" href="<?=$this->url('vitucho/default',array('controller'=>'proveedor','action'=>'index'))?>">Mantenimiento Proveedor</a>
