<?// var_dump($this->form) ?>

<?//=$this->form()->openTag($this->form);?>
<?//=$this->formCollection($this->form);?>
<?//=$this->form()->closeTag();?>


<?=$this->form()->openTag($this->form);?>
    <? if(APPLICATION_ENV!='testing'): ?>
        <?=$this->formInput($this->form->get('token'))?>
    <? endif; ?>

<h2 class="form-signin-heading" id="titulo-login">Please sign in</h2>
    <?
    // el objeto elemento (\Zend\Form\Element\Text)
    $e = $this->form->get('login');
    // tiene errores o no?
    $hasError = (bool) count($e->getMessages());
    // el primer error
    $error = $hasError ? array_values($e->getMessages())[0] : '';
    ?>
    <?=$this->formInput($e)?>
    <?=$error?>
    
    <?
    // el objeto elemento (\Zend\Form\Element\Password)
    $e = $this->form->get('pwd');
    // tiene errores o no?
    $hasError = (bool) count($e->getMessages());
    // el primer error
    $error = $hasError ? array_values($e->getMessages())[0] : '';
    ?>
    <? $e->setAttribute('class', 'form-control'); ?>
    <?=$this->formInput($e)?>
    <?=$error?>
    
    <label class="checkbox">
        <?=$this->formCheckbox($this->form->get('rememberme'))?> Remember me
    </label>
    <?=$this->formSubmit($this->form->get('enviar'))?>
    

<?=$this->form()->closeTag();?>

