
<div class="row">

    <h1>Tema Router</h1>
    
    <ul>
        <li><a href="<?=$this->url('tema-router/default',array('controller'=>'index','action'=>'destino'))?>">Ruta normal</a></li>
        <li><a href="<?=$this->url('tema-router/destino')?>">Ruta hija con nombre</a></li>
        <li><a href="<?=$this->url('destino')?>">Ruta con nombre</a></li>
        <li><a href="<?=$this->url('destino-params',array('id'=>  rand(0,999999)))?>">Ruta acepta parámetros</a></li>
        <li><a href="<?=$this->url('destino-params',array('id'=>  rand(0,99), 'pais'=>'PE'))?>">Ruta acepta parámetros 2</a></li>
        <li><a href="<?=$this->url('destino-seo',array('ciudad'=>'trujillo','pais'=>'puerto-rico','id'=>rand(0,99)))?>">Ruta SEO-friendly</a></li>
    </ul>
    
    
</div>
