<a class="btn btn-default" href="<?=$this->url('karina/default',array('controller'=>'index','action'=>'index'))?>">Back</a>
<a class="btn btn-primary" href="<?=$this->url('karina/default',array('controller'=>'categoria','action'=>'nuevo'))?>">Nuevo</a>

<?php var_dump('karito'); ?>
<div class="row">
    <h1>Karina - Categoría</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Categoría</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($this->rows as $row): ?>
            <tr class="<?=$row->getActivo()?'activo':'inactivo'?>">
                <? $id = $row->getId() ?>
                <td><?=$row->getNombre()?></td>
                <td>
                    <? $base = array('controller'=>'categoria','id'=>$id) ?>
                    <? $url = $this->url('karina/default/id',  array_merge($base,array('action'=>'editar'))) ?>
                    <a href="<?=$url?>" class="btn btn-primary btn-xs">editar</a>
                    
                    <? if(!$row->getActivo()): ?>
                        <? $url = $this->url('karina/default/id',  array_merge($base,array('action'=>'activar'))) ?>
                        <a onclick="return confirm('Seguro?')" href="<?=$url?>" class="btn btn-primary btn-xs">activar</a>
                    <? else: ?>
                        <? $url = $this->url('karina/default/id',  array_merge($base,array('action'=>'desactivar'))) ?>
                        <a onclick="return confirm('Seguro?')" href="<?=$url?>" class="btn btn-primary btn-xs">desactivar</a>
                    <? endif; ?>
                    
                    <? $url = $this->url('karina/default/id',  array_merge($base,array('action'=>'borrar'))) ?>
                    <a onclick="return confirm('Seguro?')" href="<?=$url?>" class="btn btn-warning btn-xs">borrar</a>
                </td>
            </tr>
            <? endforeach; ?>
        </tbody>
    </table>
    
</div>

<style>
    table tbody tr.activo {
        background-color: lightgreen;
    }
    table tbody tr.inactivo {
        background-color: salmon;
    }
</style>